
package sa1_gate_access_control;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;

import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class frmManager extends javax.swing.JFrame {

    /**
     * Creates new form frmManager
     */
    public frmManager() {
        initComponents();
        mVeiwRecords();
    }
    
    
    private static String strDate ,strName="", strTime ,strFromCompany , strVehicleRegNo ,strNumber
            ,strReasonForVisit ,strPersonToSee ;
    
            private  static int RecordID=0;
            
    
    
             // Data Base .......  ///
    
    
    
      private int intID;
       String strDBConnectionString= "jdbc:mysql://localhost:3306/gate_access_control?" + "useSSL=false";
      private final String strDBUser="root";
      private final String strDBPassword="Password";
      private java.sql.Connection conMySQLConnectionString;
      private Statement stStatement= null;
      private ResultSet rs= null;
   
     
      
    
    
      // method to SetData to Table  
      
  
       private void mVeiwRecords(){
         
               
                try{

            conMySQLConnectionString = DriverManager.getConnection
            (strDBConnectionString, strDBUser, strDBPassword);
            
             conMySQLConnectionString.createStatement();
            stStatement = (Statement) conMySQLConnectionString.createStatement();
            String  strQuery = "Select * from visitor_records";
            stStatement.execute(strQuery);
            rs=stStatement.getResultSet();
           
            ResultSetMetaData rsmt = rs.getMetaData();
            
            int intColumnCount = rsmt.getColumnCount();
            
            Vector vColumn = new Vector(intColumnCount);
            for(int i = 1;i < intColumnCount; i++){
            
            vColumn .add(rsmt.getCatalogName(i));
            }
            
            Vector vData = new Vector();
            Vector vRow = new Vector();
            DefaultTableModel RecordTable = (DefaultTableModel) tblViewRecord.getModel();
            while(rs.next()){
            
            vRow = new Vector(intColumnCount);
            for (int i =1 ; i <=intColumnCount; i++){
            
               vRow.add(rs.getString(i));
            
            
                 }
            
            vData.add(vRow);
             RecordTable.addRow(vRow);
            }
          
            
                       
          } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,e); 
           }finally{

                            try{

                            stStatement.close();

                            }catch(Exception e  ){

                            JOptionPane.showMessageDialog(null,"Connection String not closed "+""+e);
                            }
                   }          
    
    }
      
      
       
    
    
    
    public void mDelete(){
    
    
    
     try{

            conMySQLConnectionString = DriverManager.getConnection
            (strDBConnectionString, strDBUser, strDBPassword);
            
             conMySQLConnectionString.createStatement();
            stStatement = (Statement) conMySQLConnectionString.createStatement();
           String  strQuery = "Delete from  visitor_records  where  visitorID ='"
                  + RecordID +"'  and  name = '" +strName + "'";
          stStatement = conMySQLConnectionString.prepareStatement(strQuery);
          stStatement.execute(strQuery);
          
      
           JOptionPane.showMessageDialog(null,"Record Deleted");
                       
          } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null,e); 
           }finally{

                            try{

                            stStatement.close();

                            }catch(SQLException e  ){

                            JOptionPane.showMessageDialog(null,"Connection String not closed "+""+e);
                            }
                   }
     }
    
    
    
    
      
       
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnSaveToTextFile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlDataInputContainer = new javax.swing.JPanel();
        spnTable = new javax.swing.JScrollPane();
        tblViewRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblTittle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 255, 255));
        lblTittle.setText("Gate Access Control ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(java.awt.Color.orange);
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 70));

        btnSaveToTextFile.setBackground(java.awt.Color.orange);
        btnSaveToTextFile.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnSaveToTextFile.setText("Save to text file");
        btnSaveToTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToTextFileActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveToTextFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 330, 70));

        btnLogout.setBackground(java.awt.Color.orange);
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnLogout.setText("Exit");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 240, 70));

        pnlDataInputContainer.setBackground(new java.awt.Color(0, 0, 0));
        pnlDataInputContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlDataInputContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        spnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnTableMouseClicked(evt);
            }
        });

        tblViewRecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblViewRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Date", "Time in", "Name", "From Company", "Vehicle Reg. No.", "Tel. No", "Reason for Visit", "Person to see"
            }
        ));
        tblViewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewRecordMouseClicked(evt);
            }
        });
        spnTable.setViewportView(tblViewRecord);

        pnlDataInputContainer.add(spnTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDataInputContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDataInputContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblViewRecord.getModel();
         
        if (strName.equals("")){  // checking if data is clicked in table 
           
          
            JOptionPane.showMessageDialog(rootPane, "Data  must be selected from a table \n"
                + " hint:* Clicked data to be deleted will be highlited in blue colour!");
            
            
        }else{ 
           
            mDelete();
            model.setRowCount(0);
            mVeiwRecords();
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblViewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewRecordMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)tblViewRecord.getModel();
        int SelectedRows = tblViewRecord.getSelectedRow();
        tblViewRecord.setSelectionBackground(Color.blue);
        RecordID =Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
        strDate=(RecordTable.getValueAt(SelectedRows, 1).toString());
        strTime=(RecordTable.getValueAt(SelectedRows, 2).toString());
        strName=(RecordTable.getValueAt(SelectedRows, 3).toString());
        strFromCompany=(RecordTable.getValueAt(SelectedRows, 4).toString());
        strVehicleRegNo=(RecordTable.getValueAt(SelectedRows, 5).toString());
        strNumber=(RecordTable.getValueAt(SelectedRows, 6).toString());
        strReasonForVisit=(RecordTable.getValueAt(SelectedRows, 7).toString());
        strPersonToSee=(RecordTable.getValueAt(SelectedRows, 8).toString());
    }//GEN-LAST:event_tblViewRecordMouseClicked

    private void spnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_spnTableMouseClicked

    private void btnSaveToTextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToTextFileActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Gate Access Record:");
         MessageFormat footer = new MessageFormat("Page 1");
         
         
         try {
         
             tblViewRecord.print(JTable.PrintMode.NORMAL,header,footer );
         }catch (java.awt.print.PrinterException e){
         
            System.err.format("No printer found", e.getMessage());
         
         }
        
                
    }//GEN-LAST:event_btnSaveToTextFileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        frmMain frmMain = new frmMain();
        frmMain.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSaveToTextFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlDataInputContainer;
    private javax.swing.JScrollPane spnTable;
    private javax.swing.JTable tblViewRecord;
    // End of variables declaration//GEN-END:variables
}
